# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import assistant_pb2 as assistant__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssistantStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessQuery = channel.unary_unary(
                '/assistant.Assistant/ProcessQuery',
                request_serializer=assistant__pb2.QueryRequest.SerializeToString,
                response_deserializer=assistant__pb2.QueryReply.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/assistant.Assistant/GenerateReport',
                request_serializer=assistant__pb2.ReportRequest.SerializeToString,
                response_deserializer=assistant__pb2.ReportReply.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/assistant.Assistant/GetHistory',
                request_serializer=assistant__pb2.HistoryRequest.SerializeToString,
                response_deserializer=assistant__pb2.HistoryReply.FromString,
                _registered_method=True)


class AssistantServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=assistant__pb2.QueryRequest.FromString,
                    response_serializer=assistant__pb2.QueryReply.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=assistant__pb2.ReportRequest.FromString,
                    response_serializer=assistant__pb2.ReportReply.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=assistant__pb2.HistoryRequest.FromString,
                    response_serializer=assistant__pb2.HistoryReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assistant.Assistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assistant.Assistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Assistant(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/ProcessQuery',
            assistant__pb2.QueryRequest.SerializeToString,
            assistant__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/GenerateReport',
            assistant__pb2.ReportRequest.SerializeToString,
            assistant__pb2.ReportReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.Assistant/GetHistory',
            assistant__pb2.HistoryRequest.SerializeToString,
            assistant__pb2.HistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
