# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\x12\tassistant\"E\n\x0cQueryRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"~\n\nQueryReply\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x11\n\tartifacts\x18\x03 \x03(\t\x12\x1b\n\x13needs_clarification\x18\x04 \x01(\x08\x12\x1c\n\x14\x63larification_prompt\x18\x05 \x01(\t\"3\n\rReportRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"/\n\x0bReportReply\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"$\n\x0eHistoryRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"8\n\x0cHistoryReply\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0chistory_json\x18\x02 \x01(\t2\xd1\x01\n\tAssistant\x12>\n\x0cProcessQuery\x12\x17.assistant.QueryRequest\x1a\x15.assistant.QueryReply\x12\x42\n\x0eGenerateReport\x12\x18.assistant.ReportRequest\x1a\x16.assistant.ReportReply\x12@\n\nGetHistory\x12\x19.assistant.HistoryRequest\x1a\x17.assistant.HistoryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=30
  _globals['_QUERYREQUEST']._serialized_end=99
  _globals['_QUERYREPLY']._serialized_start=101
  _globals['_QUERYREPLY']._serialized_end=227
  _globals['_REPORTREQUEST']._serialized_start=229
  _globals['_REPORTREQUEST']._serialized_end=280
  _globals['_REPORTREPLY']._serialized_start=282
  _globals['_REPORTREPLY']._serialized_end=329
  _globals['_HISTORYREQUEST']._serialized_start=331
  _globals['_HISTORYREQUEST']._serialized_end=367
  _globals['_HISTORYREPLY']._serialized_start=369
  _globals['_HISTORYREPLY']._serialized_end=425
  _globals['_ASSISTANT']._serialized_start=428
  _globals['_ASSISTANT']._serialized_end=637
# @@protoc_insertion_point(module_scope)
